#Source Image that we are going to use for building our on top of it.
FROM httpd:latest

#Person/Organization that's maintaining image.
MAINTAINER Kamil

#Copy the index.html into directory where apache is looking for content
COPY index.html /usr/local/apache2/htdocs
